---
- name: Fill variables for deploying
  hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: template_ssh_host
      prompt: "Enter the IP of deployment server "
      private: no
    - name: template_ssh_user
      prompt: "Enter the username of deployment server "
      private: no
    - name: template_ssh_port
      prompt: "Enter the ssh port "
      default: "22"
      private: no
    - name: template_ssh_private_key
      prompt: "Enter the path which leads to your SSH private key "
      default: "~/.ssh/id_rsa"
      private: no

    - name: template_Jenkins_Secret
      prompt: "Jenkins Secret Key "
      private: no
    - name: template_Jenkins_Node_Name
      prompt: "Future slave name "
      private: no
    - name: template_Jenkins_Master_IP
      prompt: "Enter Master node IP "
      private: no
    - name: template_Jenkins_Master_Port
      prompt: "Enter Master node Port "
      default: "8080"
      private: no

  tasks:
    - template:
        src: ../templates/inventory.j2 
        dest: ../playbooks/inventory       
    - template:
        src: ../templates/variables.yml.j2 
        dest: ../playbooks/variables.yml
...