---
- name: Generate inventory
  hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: template_ssh_host
      prompt: "Enter the IP of deployment server "
      private: no
    - name: template_ssh_user
      prompt: "Enter the username of deployment server "
      private: no
    - name: template_ssh_port
      prompt: "Enter the ssh port "
      default: "22"
      private: no
    - name: template_ssh_private_key
      prompt: "Enter the path which leads to your SSH private key "
      default: "~/.ssh/id_rsa"
      private: no

  tasks:
    - template: src={{ item.src }} dest={{ item.dest }}
      with_items:
        - { src: '../templates/inventory.j2', dest: '../playbooks/inventory' }
  
- name: Include Jenkins creds 
  import_playbook: jenkins_creds.yml
...